name: publish

on:
  push:
    paths:
      - 'version.txt'

  workflow_dispatch:
    inputs:
      version:
        description: 'Target version'
        required: false
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string


jobs:
  build:
    permissions:
      contents: write
        
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip

      - run: pip install -r dev-requirements.txt

      - run: echo "version=$(python ./build.py version)" >> $GITHUB_OUTPUT
        id: version

      - run: python ./build.py build --version="${{ steps.version.outputs.version }}"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: dist/*
          body: "Automatic release"
          draft: true
          makeLatest: true
          name: GyverHub web ${{ steps.version.outputs.version }}
          tag: v${{ steps.version.outputs.version }}
